/**
 * Generated by `scripts/build-builder-catalog.mjs` from the components' TypeScript types.
 * Do not edit. Run `pnpm builder:catalog` after changing a component's props.
 *
 * Every option here was read off a prop's type, so the builder cannot offer a variant the component
 * does not have, and cannot miss one it does.
 */

/**
 * How the inspector draws a prop, and what the document is allowed to store for it.
 *
 * `image` is never generated — nothing in a TypeScript type says "this string is a picture". It is
 * asked for by hand in `registry.tsx`, and the control it draws accepts a dropped file as well as a
 * URL. It lives in this union rather than beside that override so that a spec is one type everywhere.
 */
export type ControlKind = 'enum' | 'text' | 'number' | 'boolean' | 'slot' | 'image'

export interface PropSpec {
  name: string
  kind: ControlKind
  /** For `enum`: the complete set of legal values, in the order the type declares them. */
  options?: string[]
  /** What the component does when the prop is absent, read from its `@default` tag. */
  default?: string
  /** The first sentence of the prop's documentation, shown under the control. */
  doc?: string
  /**
   * Absent when the prop was read from the component's own type — the compiler-enforced case.
   * `'story'` when the type delegated the values to the theme and the Storybook `argTypes` were the
   * only written-down list, as with `Button`'s four Figma appearances.
   */
  source?: 'story'
}

export interface ComponentSpec {
  name: string
  doc?: string
  props: PropSpec[]
  /**
   * Props whose type is richer than a generic control can honestly draw — an array of objects, a
   * render function. Listed rather than hidden: these are where a purpose-built editor goes next.
   */
  unsupported?: string[]
}

export const CATALOG: ComponentSpec[] = [
  {
    name: "Accordion",
    doc: "Accordion — Figma `Accordion` component set (node `17019:127517`).",
    props: [
      { name: "size", kind: "enum", options: ["sm", "lg"], default: "lg", doc: "Figma's `Size`: `lg` is `Default` (56px row, 21px label), `sm` is `Condensed` (40px, 18px)." },
      { name: "chevronPosition", kind: "enum", options: ["left", "right"], source: "story" },
      { name: "multiple", kind: "boolean", source: "story" },
      { name: "disableChevronRotation", kind: "boolean", source: "story" },
      { name: "chevron", kind: "slot", source: "story" },
      { name: "value", kind: "slot", source: "story" },
      { name: "defaultValue", kind: "slot", default: "hosting", source: "story" },
    ],
    unsupported: ["autoplay"],
  },
  {
    name: "Banner",
    doc: "Banner — the announcement band across the top of the site.",
    props: [
      { name: "tone", kind: "enum", options: ["brand", "accent", "neutral"], default: "brand", doc: "The wash and the pill colour." },
      { name: "label", kind: "slot", default: "New", doc: "The pill before the message — `New`, `Event`, `Beta`. Two or three words at most: it is a category, not a headline." },
      { name: "icon", kind: "slot", doc: "A glyph before the pill. One of the 20px icons; it is decorative and hidden from assistive tech." },
      { name: "children", kind: "slot", default: "Liferay DXP 2026.Q3 is generally available — self-hosted and SaaS.", doc: "The announcement itself. One sentence — the band is 40px and does not grow gracefully." },
      { name: "action", kind: "slot", doc: "Where the announcement leads — a `Link`, normally. It sits inline after the message on a wide band and wraps under it on a narrow one." },
      { name: "closeLabel", kind: "text", default: "Dismiss announcement", doc: "The dismiss button's accessible name." },
      { name: "align", kind: "enum", options: ["center", "left"], default: "center", doc: "Centred under the band, or ranged left in the page gutter with the dismiss button pushed to the far edge. Centred reads as an announcement; left reads as part of the page." },
      { name: "position", kind: "enum", options: ["static", "sticky"], default: "static", doc: "`sticky` keeps the band at the top of the viewport as the page scrolls." },
      { name: "maxWidth", kind: "number", default: "1280", doc: "The content's ceiling, matching whatever the page uses." },
      { name: "regionLabel", kind: "text", default: "Announcement", doc: "The accessible name of the region." },
      { name: "onClose", kind: "slot", source: "story" },
    ],
  },
  {
    name: "Button",
    doc: "Button — Figma `Button` component set (node `16123:189647`).",
    props: [
      { name: "variant", kind: "enum", options: ["filled", "outline", "neutral", "rounded"], default: "filled", source: "story" },
      { name: "size", kind: "enum", options: ["lg", "md", "sm"], default: "lg", source: "story" },
      { name: "leftSection", kind: "slot", source: "story" },
      { name: "rightSection", kind: "slot", source: "story" },
    ],
  },
  {
    name: "CapabilityMap",
    doc: "CapabilityMap — the product constellation from the homepage redesign (`Homepage Redesign`, node `7703:16084`): sixteen products in four sections of four, around the platform they all sit on.",
    props: [
      { name: "hubIcon", kind: "slot", doc: "The thing at the centre: `IconGlassDXP` for the product map." },
      { name: "hubLabel", kind: "slot", default: "DXP", doc: "The name under it." },
      { name: "hubHref", kind: "text", doc: "Where the hub goes, if it is a target too." },
      { name: "wash", kind: "boolean", default: "true", doc: "The gradient behind the hub — the light the whole figure sits in." },
      { name: "names", kind: "enum", options: ["nested", "outside"], default: "nested", doc: "Where each section's name goes." },
      { name: "shape", kind: "enum", options: ["hexagon", "octagon"], default: "hexagon", doc: "The tile, and the lattice under it." },
      { name: "grid", kind: "boolean", default: "true", doc: "The lattice itself, revealed under the pointer." },
      { name: "maxHeight", kind: "number", doc: "A ceiling on how tall the figure may be — a length, or a number of pixels." },
      { name: "network", kind: "boolean", default: "true", doc: "The network: traces walking the lattice, a loop around each section, and a connector from the hub out to each one." },
    ],
    unsupported: ["clusters"],
  },
  {
    name: "Card",
    doc: "Card — Figma `card-main` (node `16728:26513`), with `Surface` (`16953:109831`), `card-image`, `header-alignment` (`19097:9035`), `Card hero` (`17720:27408`) and `Content Text` (`20354:3820`).",
    props: [
      { name: "surface", kind: "enum", options: ["glass", "static", "highlighted", "none"], default: "glass", doc: "Which of the four kinds of card this is. See `CardSurface` — the choice carries the meaning, and for `static` and `highlighted` it also settles `interactive`." },
      { name: "tone", kind: "enum", options: ["blue", "purple"], default: "blue", doc: "The gradient on a `highlighted` card. Ignored by the other three." },
      { name: "align", kind: "enum", options: ["vertical", "horizontal"], default: "vertical", doc: "Figma `card-main` `Align`." },
      { name: "radius", kind: "enum", options: ["card", "pill"], default: "card", doc: "The corner." },
      { name: "padding", kind: "enum", options: ["all", "content", "full", "none"], default: "all", doc: "Where the 20px goes." },
      { name: "image", kind: "slot", doc: "`Show Image` — the `card-image` slot. Pass an `Image`, an `img`, a logo panel, anything. Present is shown and absent is hidden, which is what Figma's `Show Image` boolean does." },
      { name: "imageRatio", kind: "enum", options: ["3:2", "16:9"], default: "3:2", doc: "Figma's `Aspect Ratio` axis on `card-image`." },
      { name: "top", kind: "slot", doc: "`Show Top Content` — above the header. A `Stat` in the quote card." },
      { name: "hero", kind: "slot", doc: "`Card hero` — the thing above the title: a `Label`, a glass icon, a `Stat`, a date. Figma's `Show` axis lists Label, Icon, Blog, Tag, Events and Stat; all six are just different content here." },
      { name: "headerAlign", kind: "enum", options: ["vertical", "center"], default: "vertical", doc: "Figma `header-alignment` `Align`. `center` centres the hero and the title." },
      { name: "title", kind: "slot", doc: "`Show title` + the `Title Card` text. Named for the slot, not the HTML attribute." },
      { name: "titleSize", kind: "enum", options: ["small", "full"], default: "small", doc: "Figma `Content Text` `Size`." },
      { name: "description", kind: "slot", doc: "`Show description`." },
      { name: "main", kind: "slot", doc: "`Show Main Content 1` — under the header. A `StatBar` in the wide card." },
      { name: "secondary", kind: "slot", doc: "`Show Main Content 2` — a second block under the first." },
      { name: "bottom", kind: "slot", doc: "`Show Bottom Content` — the last block, pushed to the bottom. Links, buttons, an attribution." },
      { name: "interactive", kind: "boolean", default: "false", doc: "Turns on the hover and focus treatment." },
      { name: "children", kind: "slot", doc: "Anything else, rendered where `main` sits." },
    ],
  },
  {
    name: "Carousel",
    doc: "Carousel — the `card carousel` section (node `24465:66866`) and the Figma `Carousel` control set (node `20440:16714`).",
    props: [
      { name: "label", kind: "text", default: "Customer stories", doc: "Names the carousel for a screen reader — \"Customer stories\", \"Featured products\". Required, and not optional-with-a-default for the same reason `Image`'s `alt` is not: a region announced as \"carousel\" with no name tells someone nothing about what they have landed in." },
      { name: "slideSize", kind: "number", default: "310", doc: "The width of one slide. Figma's cards are **310px**; a number is pixels, a string is any CSS length, so `'80%'` gives the one-card-at-a-time layout where the next card peeks in." },
      { name: "gap", kind: "number", default: "13", doc: "The gap between slides. Figma's `List` uses 13px, which is not a step on the spacing scale." },
      { name: "arrows", kind: "boolean", default: "true", doc: "Figma's `Type=arrows`: the pair of 44×40 outline buttons under the track. They step one slide at a time and disable at each end." },
      { name: "indicators", kind: "enum", options: ["dots", "lines", "none"], default: "dots", doc: "Figma's two indicator styles. `dots` is the 12px dot row inside the `Type=arrows` cell; `lines` is the `Type=lines` cell, where the active bar is 64px against the inactive 24px." },
      { name: "fade", kind: "boolean", default: "true", doc: "Figma's `Overlay`: the track fades out at the edges, so a half-scrolled card reads as continuing rather than as cut off." },
      { name: "fadeWidth", kind: "number", default: "15%", doc: "How far in the fade reaches. Figma's overlay is 15% of the frame at each edge." },
      { name: "gutter", kind: "number", default: "0", doc: "Space before the first slide and after the last, inside the scroll area. Figma's `List` uses the page's 80px gutter; the default here is 0, because a gutter belongs to the page rather than to the component that sits in it." },
      { name: "header", kind: "slot", doc: "Above the track — a section heading, a description, a link. Figma puts a `Section Title` here." },
      { name: "children", kind: "slot", doc: "The slides. Each child is wrapped in its own slide, so cards go in directly." },
    ],
  },
  {
    name: "Chip",
    doc: "Chip — Figma `Chip` component set (node `16858:51126`), on Mantine's `Chip`.",
    props: [
      { name: "leftSection", kind: "slot", doc: "Figma's `Left Icon` boolean and its `↳ Left Icon` swap — a `UI Icon` before the label." },
      { name: "rightSection", kind: "slot", doc: "Figma's `Right Icon` boolean and its `↳ Right Icon` swap. Every drawn cell puts a close glyph here, which is what makes this a removable filter chip rather than a badge." },
      { name: "dragging", kind: "boolean", doc: "Figma's `State=Dragged`: the chip lifted under the pointer, with a fill and a shadow. Dragging itself is the page's job — a chip cannot know it is being reordered — so this is the styling hook a drag implementation sets, not behaviour this component provides." },
      { name: "children", kind: "text", default: "Text", source: "story" },
      { name: "disabled", kind: "boolean", default: "false", source: "story" },
    ],
  },
  {
    name: "ContentMedia",
    doc: "ContentMedia — Figma's `Content Left Image` and `Content- Right Image` sections (`17892:146518`).",
    props: [
      { name: "media", kind: "slot", doc: "The image, video, or anything else that belongs in the media column." },
      { name: "mediaSide", kind: "enum", options: ["left", "right"], default: "left" },
      { name: "mediaRatio", kind: "enum", options: ["3:2", "16:9", "auto"], default: "3:2", doc: "The media box's ratio, from `card-image`'s own axis. `auto` takes the ratio off and lets the column be as tall as what is in it — which is what the Home page's `Different Teams. One Platform.` needs, because its right column is an image *and* a row of stats under it, and a fixed 3:2 box clips the second half." },
      { name: "eyebrow", kind: "slot", doc: "Above the heading — a `Label`, an eyebrow." },
      { name: "title", kind: "slot" },
      { name: "description", kind: "slot" },
      { name: "actions", kind: "slot", doc: "Figma's `Action section`: a link, a button, or both." },
      { name: "children", kind: "slot", doc: "Anything else in the text column, under the description." },
    ],
    unsupported: ["order"],
  },
  {
    name: "Divider",
    doc: "Divider — Figma `divider` component set (node `16290:53873`).",
    props: [
      { name: "tone", kind: "enum", options: ["normal", "gradient"], default: "normal", doc: "Figma's `Property 1`." },
      { name: "orientation", kind: "enum", options: ["horizontal", "vertical"], default: "horizontal", doc: "Figma's `Property 2`." },
      { name: "labelPosition", kind: "enum", options: ["left", "center", "right"], source: "story" },
      { name: "label", kind: "text", source: "story" },
    ],
  },
  {
    name: "Footer",
    doc: "Footer — Figma `LRDC footer` component set (node `16288:12662`).",
    props: [
      { name: "cta", kind: "slot", doc: "Figma's `Page Action Section` — the grey band above the footer proper, holding a centred heading and a signup field. A `Section` with a `Form` in it is what goes here." },
      { name: "stats", kind: "slot", doc: "Figma's `Number Footer` — the blue strip of figures between the CTA and the dark band. A `StatBar`." },
      { name: "brand", kind: "slot", doc: "`Footer.Brand`, which Figma puts first in the second row of columns." },
      { name: "children", kind: "slot", doc: "`Footer.Column`s. They lay out in a grid that reflows on its own." },
      { name: "legal", kind: "slot", doc: "Figma's `Subfooter Content` — the copyright and legal links along the bottom." },
      { name: "backdrop", kind: "slot", doc: "The dark band's artwork — Figma layers a bubble image behind the content. Not bundled, for the reason the Hero's is not: it is a multi-megabyte asset that belongs to the page, not inside a component's JavaScript. Pass an `img` or a `video`; without one the band is its own dark ground and the vignette." },
    ],
  },
  {
    name: "Form",
    doc: "Form — Figma `Form` component set (node `21405:74359`).",
    props: [
      { name: "title", kind: "slot", default: "Start your free 30 day trial", doc: "Figma's `Content Text` title — 28px semibold on the desktop card, 23px on a narrow one." },
      { name: "description", kind: "slot", default: "No credit card required, and nothing installs on your machine.", doc: "The line under it." },
      { name: "terms", kind: "slot", doc: "Figma's `Description/Terms` slot: the reCAPTCHA and privacy line. It sits **above** the submit button, which is where the file puts it and where it belongs — terms you agree to by submitting have to be readable before the button, not after it." },
      { name: "submit", kind: "slot", doc: "The submit control. Figma draws a full-width `Size=Medium` solid button." },
      { name: "footnote", kind: "slot", doc: "The line under the button — Figma's second `Description Card`, for an \"already have an account?\" link." },
      { name: "children", kind: "slot", doc: "`Form.Row`s, or anything else that belongs between the heading and the terms." },
    ],
  },
  {
    name: "Header",
    doc: "Header — the primary navigation, with a mega menu per section.",
    props: [
      { name: "logo", kind: "slot", doc: "The brand, top left." },
      { name: "actions", kind: "slot", doc: "The right-hand side: language, account, a call to action." },
      { name: "defaultOpen", kind: "text", doc: "Which menu is open on mount. The prototype opens Platform so the first section is visible immediately; a real page almost always wants `null`." },
      { name: "position", kind: "enum", options: ["fixed", "static"], doc: "`fixed` overlays the page, which is what the glass blur is for. `static` sits in the flow." },
      { name: "condense", kind: "boolean", default: "true", doc: "Condense on scroll: at the top of the page the band is transparent and part of the hero, and once the page moves it gains the glass, the hairline and a tighter bar." },
      { name: "items", kind: "slot", source: "story" },
      { name: "drawerControls", kind: "slot", source: "story" },
    ],
    unsupported: ["onOpenChange"],
  },
  {
    name: "Hero",
    doc: "Hero — Figma `Hero` component set (node `19110:9503`), with the slots the accompanying spreadsheet lists.",
    props: [
      { name: "background", kind: "enum", options: ["none", "full", "corner"], default: "corner", doc: "Figma's `Type` axis, and the spreadsheet's Background column: `full` is Bubble Full, `corner` is Corner Bubble, `none` is the plain surface." },
      { name: "drawn", kind: "boolean", doc: "Draw the bubble instead of playing a file — the prototype the bubble lab exists to judge." },
      { name: "align", kind: "enum", options: ["left", "center"], default: "left", doc: "`center` centres the column and its text." },
      { name: "banner", kind: "slot", doc: "A full-width band above the content and the media, centred in the hero's own gutters. The Home page (node `24563:52720`) draws a solution finder there — a 1000px bar sitting over the bubble, above the heading and spanning both columns — which none of the content slots can hold, because every one of them lives inside the left column." },
      { name: "label", kind: "slot", doc: "Above the heading — a `Label`, an eyebrow, a breadcrumb." },
      { name: "title", kind: "slot", doc: "The heading. Pass a real `h1` — the hero does not choose a heading level for you, because only the page knows whether this is its first heading. Named `title` for the slot it fills, not the `title` attribute." },
      { name: "description", kind: "slot", default: "Build once and deliver everywhere — websites, portals, commerce and search on one DXP.", doc: "A line or two under the heading." },
      { name: "actions", kind: "slot", doc: "Buttons and links, in the order they should be read." },
      { name: "form", kind: "slot", doc: "The `Form` type: an email field with a contained button, in place of the buttons. Both can be present, but one of them is usually the point." },
      { name: "proof", kind: "slot", doc: "The Gartner logo and its tags, or any other proof that sits under the actions." },
      { name: "media", kind: "slot", doc: "Figma's `Image=Yes`: the media column beside the content. An image, a video card, anything." },
      { name: "children", kind: "slot" },
      { name: "videoLight", kind: "slot", source: "story" },
      { name: "videoPoster", kind: "slot", source: "story" },
    ],
    unsupported: ["video"],
  },
  {
    name: "Image",
    doc: "Image — the ratios from Figma's `Aspect Ratio` set (node `12305:1754909`), on Mantine's `Image`.",
    props: [
      { name: "ratio", kind: "enum", options: ["3:2", "16:9", "auto", "1:1", "4:3", "16:10", "2:1", "5:2", "3:1", "40:33"], default: "3:2", doc: "The box's aspect ratio, from Figma's `Aspect Ratio` set. `auto` is its `Adjustable` cell: no ratio, so the image sets its own height." },
      { name: "orientation", kind: "enum", options: ["horizontal", "vertical"], default: "horizontal", doc: "Figma's second axis. `vertical` inverts the ratio — a vertical `3:2` is 2:3 — which is how the set draws its portrait cells rather than listing them separately." },
      { name: "fit", kind: "enum", options: ["cover", "contain", "fill", "none", "scale-down"], default: "cover", doc: "How the image fills its box, when a `ratio` gives it one." },
      { name: "fill", kind: "boolean", doc: "Makes the image fill its nearest positioned ancestor — `position: absolute` on all four edges — for a cover layer behind content. The parent needs `position: relative` and its own size; without a positioned parent the image will fill the page." },
      { name: "alt", kind: "text", default: "", doc: "Required, and empty is a valid answer: `alt=\"\"` for an image that adds nothing a screen reader needs — a decorative photograph beside text that already says it. Anything else gets a sentence." },
      { name: "src", kind: "slot", source: "story" },
    ],
  },
  {
    name: "Label",
    doc: "Label — Figma `Label CTA` component set (node `15121:237267`).",
    props: [
      { name: "variant", kind: "enum", options: ["filled", "glass", "gradient"], default: "filled", doc: "Figma Style — named Gradient / Tonal / Outline there. `filled` is the two-stop gradient, `light` the flat tonal fill, `outline` the gradient stroke on no fill." },
      { name: "size", kind: "enum", options: ["sm", "md", "lg"], default: "lg", doc: "Figma Size. Large 40px, Medium 32px, Small 22px tall, each with its own corner radius." },
      { name: "leftSection", kind: "slot", doc: "Icon placed before the label — Figma's `Show Icon`." },
      { name: "rightSection", kind: "slot", doc: "Icon placed after the label. Not an axis in Figma; the icon slot there is leading only." },
      { name: "radius", kind: "enum", options: ["round", "md", "sm"], source: "story" },
    ],
  },
  {
    name: "Link",
    doc: "Link — Figma `Link` component set (node `2144:143689`).",
    props: [
      { name: "variant", kind: "enum", options: ["default", "secondary"], default: "default", doc: "Figma Style — named Primary / Secondary there. `default` is the blue link; `secondary` is the neutral one for dark surfaces." },
      { name: "size", kind: "enum", options: ["sm", "md", "lg"], default: "lg", doc: "Figma Size. Large 21px, Medium 18px, Small 14px, each with its own icon box." },
      { name: "leftSection", kind: "slot", doc: "Icon placed before the label — Figma's `Icon Left`." },
      { name: "rightSection", kind: "slot", doc: "Icon placed after the label — Figma's `Icon Right`, the usual CTA arrow." },
      { name: "disabled", kind: "boolean", doc: "Renders the link as unavailable. The `href` is dropped, so the element stops being a link entirely: not focusable, not activatable, and announced as disabled." },
      { name: "underline", kind: "enum", options: ["never", "hover", "always"], source: "story" },
    ],
  },
  {
    name: "List",
    doc: "List — Figma `List` (node `19130:63824`), `Main List Item` (`19660:37508`), `Sub List Item` (`19660:53930`) and the `Sub Item List` marker set (`19129:50376`), on Mantine's `List`.",
    props: [
      { name: "marker", kind: "enum", options: ["check", "number", "bullet", "none"], default: "check", doc: "Figma's `List` `Type`." },
      { name: "size", kind: "enum", options: ["sm", "md", "lg"], default: "md", doc: "The marker's box. Does not change the text." },
      { name: "icon", kind: "slot", doc: "Swaps the glyph for the `check` marker — Figma's `Icon Type` instance swap. Set it on the list for every item, or on a single `List.Item`." },
      { name: "spacing", kind: "number", doc: "Between items. Figma's `List` uses 20 and its `Sub List` 8, which are the two defaults." },
      { name: "padded", kind: "boolean", default: "false", doc: "Figma's `Main List Item` `Padding=Yes`: each item gets 20/16 of padding and the `Surfaces/Card BG/Grey` surface behind it. The two are one cell in Figma, so they are one prop here." },
      { name: "children", kind: "slot", source: "story" },
    ],
  },
  {
    name: "Logo",
    doc: "Logo — the Liferay lockup.",
    props: [
      { name: "variant", kind: "enum", options: ["full", "mark"], default: "full", doc: "`full` is the mark and the wordmark together; `mark` is the glyph alone, for a collapsed header or a favicon-sized slot." },
      { name: "height", kind: "number", default: "48", doc: "The rendered height in pixels. The width follows the artwork's own ratio — a logo is pinned by height, because that is what makes it sit level with the text beside it." },
      { name: "title", kind: "text", default: "Liferay", doc: "The accessible name. `Liferay` by default; pass `''` when the logo sits beside a visible wordmark or inside a link that already names itself, so it is not read out twice." },
    ],
  },
  {
    name: "Marquee",
    doc: "Marquee — the `marque` section (node `24465:67388`) and the Figma `Logos scrolling section` set (`22522:24157`).",
    props: [
      { name: "label", kind: "text", default: "Customers", doc: "Names the strip for a screen reader — \"Customers\", \"Integrations\". Required, and required for the same reason `Image`'s `alt` is: a region with no name tells someone nothing about what it holds." },
      { name: "size", kind: "enum", options: ["sm", "md", "lg"], default: "lg", doc: "Figma's `Size`, as the logo cell's height." },
      { name: "gap", kind: "number", default: "60", doc: "Between logos. Figma's grid uses 60." },
      { name: "logoWidth", kind: "number", default: "109", doc: "The width of one logo cell. Figma's is 109 and constant across its `Size` axis — the logos are fitted by width and take their height from their own proportions, which is what keeps a row of mismatched wordmarks looking level." },
      { name: "speed", kind: "number", default: "60", doc: "How fast it moves, in **pixels per second** — not a duration. A duration would make the strip speed up as logos are added; pixels per second is the same speed whatever is in it, which is why the animation's duration is measured rather than set." },
      { name: "direction", kind: "enum", options: ["left", "right"], default: "left", doc: "Which way it travels." },
      { name: "fade", kind: "boolean", default: "true", doc: "Figma's `Overlay`: the strip fades out at both edges." },
      { name: "fadeWidth", kind: "number", default: "20%", doc: "How far the fade reaches. Figma's overlay is opaque from 20% to 80%." },
      { name: "monochrome", kind: "boolean", default: "true", doc: "Figma's one-colour logo treatment: every logo inked in `Surfaces/Text/Primary`, which inverts with the colour scheme — so it covers both the `Theme=Dark` and `Theme=Light` cells at once." },
      { name: "withControl", kind: "boolean", default: "true", doc: "The pause button. **On by default, and it is not decoration**: WCAG 2.2.2 requires a way to stop motion that starts on its own and runs for more than five seconds, which an endless strip does by definition. Turn it off only if the page provides its own control." },
      { name: "pauseOnHover", kind: "boolean", default: "true", doc: "Stops while the pointer is over the strip, so a logo can be read or clicked." },
      { name: "playing", kind: "boolean", doc: "Controlled play state." },
      { name: "defaultPlaying", kind: "boolean", default: "true", doc: "Uncontrolled initial play state." },
      { name: "children", kind: "slot", doc: "The logos. Each child becomes one cell." },
    ],
    unsupported: ["onPlayingChange"],
  },
  {
    name: "Section",
    doc: "Section — the shell every block in Figma's `Section` set (node `17892:146518`) is built on.",
    props: [
      { name: "spacing", kind: "enum", options: ["default", "tight", "none"], default: "default" },
      { name: "bleed", kind: "boolean", doc: "Lets the body run to the viewport's edges while the heading and the footer keep the gutter — which is how Figma's `Integrations Section` and `Carousel` sections are built, so a marquee or a card track can bleed off the side of the page." },
      { name: "reveal", kind: "boolean", doc: "Drift the section up into place as it scrolls into view." },
      { name: "title", kind: "slot", doc: "The heading block. A `SectionTitle`, normally." },
      { name: "footer", kind: "slot", doc: "Below the body — Figma's `Call to Action` and carousel controls both sit here." },
      { name: "gap", kind: "number", doc: "Between the heading, the body and the footer. Figma uses 24, and 32 in the integrations section." },
      { name: "maxWidth", kind: "number", default: "1280", doc: "The content column's ceiling. Figma's is 1280 inside a 1440 frame." },
      { name: "children", kind: "slot" },
    ],
  },
  {
    name: "SectionTitle",
    doc: "SectionTitle — Figma `Section Title` (node `17892:146487`).",
    props: [
      { name: "title", kind: "slot", doc: "Figma's `Title`. Rendered as a real heading — see `order`." },
      { name: "description", kind: "slot", doc: "Figma's `Description`." },
      { name: "actions", kind: "slot", doc: "Figma's `Slot`: a button or a link beside the heading on a wide screen, and under it on a narrow one. The `Centered- Description` cell has no slot, but centring one is harmless and occasionally wanted." },
      { name: "align", kind: "enum", options: ["left", "center"], default: "left", doc: "Figma's `Type`: `Left- Description` or `Centered- Description`." },
    ],
    unsupported: ["order"],
  },
  {
    name: "Select",
    doc: "Select — Figma `Input` set (node `16166:23969`), `Type=Dropdown`, with the menu from the `Dropdown` set (`16884:46299`).",
    props: [
      { name: "info", kind: "slot", doc: "Figma's `Info Button`: an explanation beside the label, in a tooltip." },
      { name: "floating", kind: "boolean", doc: "Figma's `Condensed` axis — the notched label chip sitting on the field's border rather than above it." },
    ],
  },
  {
    name: "Stat",
    doc: "Stat — Figma `Stats Item` component set (node `15121:237366`).",
    props: [
      { name: "value", kind: "slot", default: "845", doc: "The number itself — Figma's `Value` text property." },
      { name: "label", kind: "slot", default: "Months to launch", doc: "The caption under it — Figma's `Label` text property." },
      { name: "size", kind: "enum", options: ["md", "sm"], default: "md", doc: "Figma's `Property 1`: Default (40px value) or Small (32px)." },
      { name: "leftSection", kind: "slot", doc: "Icon before the number — Figma's `Show Stat Icon Left`." },
      { name: "rightSection", kind: "slot", doc: "Icon after the number — Figma's `Show Stat Icon Right`." },
      { name: "align", kind: "enum", options: ["left", "center"], doc: "Left as drawn, or centred for a stat sitting alone in a card." },
    ],
  },
  {
    name: "StatBar",
    props: [
      { name: "children", kind: "slot", doc: "The stats. Anything is accepted, but this is drawn for `Stat` children." },
      { name: "align", kind: "enum", options: ["left", "center"], doc: "Figma's `Align` axis — Left as drawn, or centred." },
    ],
  },
  {
    name: "Tabs",
    doc: "Tabs — two things Figma draws as separate components, both of which are tabs.",
    props: [
      { name: "variant", kind: "enum", options: ["default", "pills"], source: "story" },
      { name: "inverted", kind: "boolean", source: "story" },
      { name: "orientation", kind: "enum", options: ["vertical", "horizontal"], source: "story" },
    ],
  },
  {
    name: "TextInput",
    doc: "TextInput — Figma `Input` set (node `16166:23969`), `Type=Text`.",
    props: [
      { name: "floating", kind: "boolean", doc: "Figma's `Condensed=True` cell: the label sits inside the 48px box and shrinks up out of the way once the field has a value or focus, rather than sitting above it." },
      { name: "info", kind: "slot", doc: "Figma's `Info Button`: an explanation beside the label, in a tooltip." },
      { name: "containedButton", kind: "slot", doc: "A button inside the field's right edge — a submit for a single-field form. Not drawn in Figma; composed from the drawn field and this library's `Button`." },
    ],
  },
  {
    name: "Textarea",
    doc: "Textarea — Figma `Input` set (node `16166:23969`), `Type=Text Area`.",
    props: [
      { name: "info", kind: "slot", doc: "Figma's `Info Button`: an explanation beside the label, in a tooltip." },
    ],
  },
]

export const componentSpec = (name: string): ComponentSpec | undefined =>
  CATALOG.find((entry) => entry.name === name)
