/**
 * AUTO-GENERATED by scripts/build-icons.mjs from @mingcute/svg@3.0.2.
 * Do not edit by hand — add the icon's MingCute name to src/icons/manifest.json and run `pnpm icons`.
 *
 * Icons are sized with `width`/`height` of `1em` so they scale with the surrounding text by default;
 * a component that fixes an icon box (Button, Link) overrides that in CSS. Colour comes from
 * `currentColor`, so an icon inherits whatever it sits in. `aria-hidden` is set because these are
 * decorative next to a label — give the icon a label at the call site if it is ever used alone.
 *
 * MingCute is Apache-2.0. See node_modules/@mingcute/svg/LICENSE.
 */
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

/** MingCute `alert` (regular, system). */
export function IconAlert(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v4m0 3h.002m-8.636 3.353h17.268a.5.5 0 0 0 .433-.75L12.433 3.648a.5.5 0 0 0-.866 0L2.933 18.603a.5.5 0 0 0 .433.75"/>
    </svg>
  )
}

/** MingCute `arrow_down` (regular, arrow). */
export function IconArrowDown(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 19V4M6.343 14 12 19.657 17.657 14"/>
    </svg>
  )
}

/** MingCute `arrow_left` (regular, arrow). */
export function IconArrowLeft(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h15m-10 5.657L4.343 12 10 6.343"/>
    </svg>
  )
}

/** MingCute `arrow_right` (regular, arrow). */
export function IconArrowRight(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 12h15m-5 5.657L19.657 12 14 6.343"/>
    </svg>
  )
}

/** MingCute `arrow_up` (regular, arrow). */
export function IconArrowUp(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 20V5m-5.657 5L12 4.343 17.657 10"/>
    </svg>
  )
}

/** MingCute `book_2` (regular, education). */
export function IconBook2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m19 17-.553 1.106a2 2 0 0 0 0 1.788L19 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11a1 1 0 0 1 1 1zm0 4H7.01a2 2 0 1 1 0-4H19m0 0h-2m-7-9h4"/>
    </svg>
  )
}

/** MingCute `box_3` (regular, files). */
export function IconBox3(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M13 11.99a1 1 0 0 0-2 0zm-2 8.51a1 1 0 1 0 2 0zm1.75-8.934.5.866zm-1.5.001-.5.866zm1.5 9 .5.866zm-1.5 0-.5.866zm7.794-3.634-.5-.866zm-6.294-13.5-.5.866 6.294 3.634.5-.866.5-.866-6.294-3.634zm7.044 4.933h-1v7.268h2V8.366zm-.75 8.567-.5-.866-6.294 3.634.5.866.5.866 6.294-3.634zm-7.794 3.634.5-.866-6.294-3.634-.5.866-.5.866 6.294 3.634zm-7.044-4.933h1V8.366h-2v7.268zm.75-8.567.5.866 6.294-3.634-.5-.866-.5-.866-6.294 3.634zM19.78 7.5l-.5-.866-7.03 4.066.5.866.5.866 7.03-4.066zm-8.53 4.067.5-.866L4.7 6.634l-.5.866-.5.866 7.05 4.067zm.75.423h-1v8.51h2v-8.51zm.75-.424-.5-.866a.5.5 0 0 1-.5 0l-.5.867-.5.866a2.5 2.5 0 0 0 2.5-.001zm-8.544-3.2h1a.5.5 0 0 1 .25-.433l-.5-.866-.5-.866a2.5 2.5 0 0 0-1.25 2.165zm.75 8.567.5-.866a.5.5 0 0 1-.25-.433h-2a2.5 2.5 0 0 0 1.25 2.165zm7.794 3.634-.5-.866a.5.5 0 0 1-.5 0l-.5.866-.5.866a2.5 2.5 0 0 0 2.5 0zm7.044-4.933h-1a.5.5 0 0 1-.25.433l.5.866.5.866a2.5 2.5 0 0 0 1.25-2.165zm-.75-8.567-.5.866a.5.5 0 0 1 .25.433h2a2.5 2.5 0 0 0-1.25-2.165zM12.75 3.433l.5-.866a2.5 2.5 0 0 0-2.5 0l.5.866.5.866a.5.5 0 0 1 .5 0z"/>
    </svg>
  )
}

/** MingCute `brackets_angle` (regular, development). */
export function IconBracketsAngle(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m9 4-5 8 5 8m6-16 5 8-5 8"/>
    </svg>
  )
}

/** MingCute `building_2` (regular, buildings). */
export function IconBuilding2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 20h18M5 20V6.36a.5.5 0 0 1 .342-.474l8-2.667a.5.5 0 0 1 .658.475V20m0-10 4.598.92a.5.5 0 0 1 .402.49V20"/>
    </svg>
  )
}

/** MingCute `bulb` (regular, devices). */
export function IconBulb(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 21h2m0-14-2 2 2 2-2 2M5 9.933c0 3.986 3.047 6.398 3.822 6.947.116.082.219.181.297.3L10 18.5h4l.88-1.32q.122-.178.298-.3C15.953 16.33 19 13.92 19 9.933 19 6.104 15.866 3 12 3S5 6.104 5 9.933"/>
    </svg>
  )
}

/** MingCute `chart_line` (regular, business). */
export function IconChartLine(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 5v14h16M6.783 14.182l4.242-4.243 3.536 3.536L20.036 8H17"/>
    </svg>
  )
}

/** MingCute `check` (regular, system). */
export function IconCheck(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m3.514 11.83 5.657 5.656L20.485 6.172"/>
    </svg>
  )
}

/** MingCute `close` (regular, system). */
export function IconClose(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="m5.636 5.637 12.728 12.728m-12.728 0L18.364 5.637"/>
    </svg>
  )
}

/** MingCute `department` (regular, development). */
export function IconDepartment(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinejoin="round" strokeWidth="2" d="M12 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm0 0v4m-6 4a2 2 0 1 0 0 4 2 2 0 0 0 0-4Zm0 0v-2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v2m0 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z"/>
    </svg>
  )
}

/** MingCute `document_2` (regular, files). */
export function IconDocument2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 3v5.5a.5.5 0 0 0 .5.5H19M9 16h6m-6-4h1m3.586-9H6a1 1 0 0 0-1 1v16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V8.414a1 1 0 0 0-.293-.707l-4.414-4.414A1 1 0 0 0 13.586 3"/>
    </svg>
  )
}

/** MingCute `down` (regular, arrow). */
export function IconDown(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 9.343 12 15 6.343 9.343"/>
    </svg>
  )
}

/** MingCute `down_small` (filled, arrow). */
export function IconDownSmallFilled(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" fillRule="evenodd" d="M12.707 14.535a1 1 0 0 1-1.414 0l-2.829-2.828A1 1 0 0 1 9.172 10h5.656a1 1 0 0 1 .708 1.707z" clipRule="evenodd"/>
    </svg>
  )
}

/** MingCute `external_link` (regular, files). */
export function IconExternalLink(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h6m9 2V4h-5m-5 10 9.5-9.5"/>
    </svg>
  )
}

/** MingCute `facebook` (regular, brands). */
export function IconFacebook(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm0 0v-8m2.5-5H14a2 2 0 0 0-2 2v3m0 0h-2m2 0h2"/>
    </svg>
  )
}

/** MingCute `folder_2` (regular, files). */
export function IconFolder2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="M3 10h18M9.52 4H4a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1h16a1 1 0 0 0 1-1V7.5a1 1 0 0 0-1-1h-7.52a1 1 0 0 1-.78-.375l-1.4-1.75A1 1 0 0 0 9.52 4Z"/>
    </svg>
  )
}

/** MingCute `github` (regular, brands). */
export function IconGithub(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M3 16c1.5.5 1.5 3.5 5 3l1-.2m6 2.2v-3c0-.86-.363-1.636-.943-2.183a.01.01 0 0 1 .005-.018C17.48 15.117 20 12.78 20 10.001c0-1.262-.52-2.433-1.406-3.399a.01.01 0 0 1-.002-.01c.632-1.537.048-3.52-.096-3.591-.139-.07-1.957.288-3.45 1.445a.01.01 0 0 1-.009.002A10.3 10.3 0 0 0 12 4c-1.076 0-2.103.16-3.04.449a.01.01 0 0 1-.009-.002C7.458 3.29 5.64 2.931 5.5 3.001c-.144.072-.728 2.057-.095 3.593a.01.01 0 0 1-.002.01C4.518 7.57 4 8.74 4 10.002c0 2.779 2.52 5.116 5.938 5.798a.01.01 0 0 1 .005.018A3 3 0 0 0 9 18v3"/><path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M3 16c1.5.5 1.5 3.5 5 3l1-.2m6 2.2v-3c0-.86-.363-1.636-.943-2.183a.01.01 0 0 1 .005-.018C17.48 15.117 20 12.78 20 10.001c0-1.262-.52-2.433-1.406-3.399a.01.01 0 0 1-.002-.01c.632-1.537.048-3.52-.096-3.591-.139-.07-1.957.288-3.45 1.445a.01.01 0 0 1-.009.002A10.3 10.3 0 0 0 12 4c-1.076 0-2.103.16-3.04.449a.01.01 0 0 1-.009-.002C7.458 3.29 5.64 2.931 5.5 3.001c-.144.072-.728 2.057-.095 3.593a.01.01 0 0 1-.002.01C4.518 7.57 4 8.74 4 10.002c0 2.779 2.52 5.116 5.938 5.798a.01.01 0 0 1 .005.018A3 3 0 0 0 9 18v3"/>
    </svg>
  )
}

/** MingCute `group` (regular, users). */
export function IconGroup(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M20 18a1 1 0 1 0 2 0zm-5 1a1 1 0 1 0 2 0zM2 19a1 1 0 1 0 2 0zm15-5v1h2v-2h-2zm4 2h-1v2h2v-2zm-1-7h-1a1 1 0 0 1-1 1v2a3 3 0 0 0 3-3zm-2 2v-1a1 1 0 0 1-1-1h-2a3 3 0 0 0 3 3zm-2-2h1a1 1 0 0 1 1-1V6a3 3 0 0 0-3 3zm2-2v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3zM6 14v1h7v-2H6zm10 3h-1v2h2v-2zM3 19h1v-2H2v2zM13 7.5h-1A2.5 2.5 0 0 1 9.5 10v2A4.5 4.5 0 0 0 14 7.5zM9.5 11v-1A2.5 2.5 0 0 1 7 7.5H5A4.5 4.5 0 0 0 9.5 12zM6 7.5h1A2.5 2.5 0 0 1 9.5 5V3A4.5 4.5 0 0 0 5 7.5zM9.5 4v1A2.5 2.5 0 0 1 12 7.5h2A4.5 4.5 0 0 0 9.5 3zM13 14v1a2 2 0 0 1 2 2h2a4 4 0 0 0-4-4zm-7 0v-1a4 4 0 0 0-4 4h2a2 2 0 0 1 2-2zm13 0v1a1 1 0 0 1 1 1h2a3 3 0 0 0-3-3z"/>
    </svg>
  )
}

/** MingCute `information` (regular, system). */
export function IconInformation(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8h.002M11 11h1v6h.5m8.5-5a9 9 0 1 1-18 0 9 9 0 0 1 18 0"/>
    </svg>
  )
}

/** MingCute `instagram` (regular, brands). */
export function IconInstagram(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M16.5 7.5h.002M15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0m-7 8h8a4 4 0 0 0 4-4V8a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v8a4 4 0 0 0 4 4"/>
    </svg>
  )
}

/** MingCute `layout_grid` (regular, design). */
export function IconLayoutGrid(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="M4 12h16m-8-8v16m-7 0h14a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v14a1 1 0 0 0 1 1Z"/>
    </svg>
  )
}

/** MingCute `linkedin` (regular, brands). */
export function IconLinkedin(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 8h.002M8 11v5m3-6v2m0 0v4m0-4c0-.5.917-1.783 2-2 1.38-.276 3 .5 3 2v4M6 20h12a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2"/>
    </svg>
  )
}

/** MingCute `menu` (regular, editing). */
export function IconMenu(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M4 6h16M4 12h16M4 18h16"/>
    </svg>
  )
}

/** MingCute `mind_map` (regular, system). */
export function IconMindMap(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="M15 12.5a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0Zm0 0h3m0 0a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0ZM6.652 8.46l2.16 1.8m4.555-3.362-.76 2.28m2.832 8.261-2.015-2.015M7.376 17.55l1.933-2.32M16 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0Zm2 13.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0ZM7 7.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0ZM8 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z"/>
    </svg>
  )
}

/** MingCute `monitor` (regular, devices). */
export function IconMonitor(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M7.757 19.03a1 1 0 1 0 .486 1.94L8 20zm8 1.94a1 1 0 1 0 .486-1.94L16 20zm4.06-4.173-.158.987zM21 6.2h-1v9.6h2V6.2zM3 15.8h1V6.2H2v9.6zm16.818.997.158-.987a49.5 49.5 0 0 0-15.952 0l.158.987.159.987a47.5 47.5 0 0 1 15.318 0zM4.182 5.203l-.158.987a49.5 49.5 0 0 0 15.952 0l-.158-.987-.159-.987a47.5 47.5 0 0 1-15.318 0zM12 16.5h-1v3h2v-3zM8 20l.242.97h.003l.013-.004.295-.066a19 19 0 0 1 .861-.164A16 16 0 0 1 12 20.5v-2c-1.076 0-2.135.134-2.914.264a21 21 0 0 0-1.32.264l-.005.001h-.003zm4-.5v1c.924 0 1.865.116 2.586.236a19 19 0 0 1 1.172.234 463 463 0 0 1 .484-1.94l-.003-.001-.006-.002-.02-.005-.076-.017-.271-.06c-.231-.05-.56-.116-.952-.181-.779-.13-1.838-.264-2.914-.264zm-9-3.7H2c0 1.256 1.132 2.178 2.34 1.984l-.158-.987-.158-.987h-.011l-.01-.006-.004-.004.001.002V15.8zm18 0h-1v.002-.002l-.003.004-.01.005-.004.001h-.007l-.158.987-.159.987C20.87 17.978 22 17.056 22 15.8zm0-9.6h1c0-1.256-1.132-2.178-2.34-1.984l.158.987.158.987h.011l.01.006.004.004L20 6.198V6.2zm-18 0h1v-.002.002l.003-.004.01-.005.004-.001h.007l.158-.987.159-.987C3.13 4.022 2 4.944 2 6.2z"/>
    </svg>
  )
}

/** MingCute `pause` (regular, media). */
export function IconPause(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M8 5v14m8-14v14"/>
    </svg>
  )
}

/** MingCute `play` (regular, media). */
export function IconPlay(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="M6.661 4.88a.47.47 0 0 1 .656-.378c1.032.441 3.375 1.502 6.354 3.222s5.071 3.22 5.97 3.893a.468.468 0 0 1 0 .755c-.889.667-2.954 2.148-5.97 3.89-3.019 1.742-5.334 2.79-6.356 3.226a.468.468 0 0 1-.653-.378c-.135-1.11-.389-3.662-.389-7.116 0-3.452.254-6.003.388-7.115Z"/>
    </svg>
  )
}

/** MingCute `presentation_1` (regular, business). */
export function IconPresentation1(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m8.46 21 3.535-3.535L15.532 21M3 4h18M8 12v1m4-3v3m4-5v5M4 4h16v12a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/>
    </svg>
  )
}

/** MingCute `question` (regular, system). */
export function IconQuestion(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 17h.002m-2.627-6.875a2.625 2.625 0 1 1 3.601 2.438c-.512.205-.976.635-.976 1.187V14m9-2a9 9 0 1 1-18 0 9 9 0 0 1 18 0"/>
    </svg>
  )
}

/** MingCute `refresh_2` (regular, system). */
export function IconRefresh2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3.811 8.264A9 9 0 0 1 14.33 3.307a9 9 0 0 1 6.672 8.622c0 .08-.088.126-.154.082l-2.678-1.804c-.091-.062-.03-.205.078-.181L20 10.41m.189 5.327c-1.789 3.932-6.208 6.112-10.519 4.956a9 9 0 0 1-6.672-8.622c0-.08.088-.126.154-.082l2.678 1.805c.091.061.03.204-.078.18L4 13.59"/>
    </svg>
  )
}

/** MingCute `right` (regular, arrow). */
export function IconRight(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.343 6.343 15 12l-5.657 5.657"/>
    </svg>
  )
}

/** MingCute `search` (regular, files). */
export function IconSearch(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="m15.879 15.879 4.242 4.242M18 10.5a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/>
    </svg>
  )
}

/** MingCute `shield_shape` (regular, shapes). */
export function IconShieldShape(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="m11.649 3.132-7 2.625A1 1 0 0 0 4 6.693v5.363a8 8 0 0 0 4.422 7.155l3.354 1.677a.5.5 0 0 0 .448 0l3.354-1.677A8 8 0 0 0 20 12.056V6.693a1 1 0 0 0-.649-.936l-7-2.625a1 1 0 0 0-.702 0Z"/>
    </svg>
  )
}

/** MingCute `shopping_cart_1` (regular, business). */
export function IconShoppingCart1(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M8 20.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m10 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0"/><path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3 3h.138a2 2 0 0 1 1.995 1.858l.8 11.213a1 1 0 0 0 .998.929h11.234a1 1 0 0 0 .984-.821l1.637-9A1 1 0 0 0 19.802 6H6m2 14.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m10 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0"/>
    </svg>
  )
}

/** MingCute `social_x` (regular, brands). */
export function IconSocialX(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M19.753 4.659a1 1 0 0 0-1.506-1.317L19 4zM4.247 19.342a1 1 0 0 0 1.506 1.317L5 20zM4 4V3a1 1 0 0 0-.8 1.6zm4 0 .8-.6A1 1 0 0 0 8 3zm12 16v1a1 1 0 0 0 .8-1.6zm-4 0-.8.6a1 1 0 0 0 .8.4zm3-16-.753-.659-5.923 6.77.753.658.752.659 5.924-6.77zm-8.077 9.23-.752-.658-5.924 6.77L5 20l.753.659 5.923-6.77zM4 4v1h4V3H4zm4 0-.8.6 12 16 .8-.6.8-.6-12-16zm12 16v-1h-4v2h4zm-4 0 .8-.6-12-16L4 4l-.8.6 12 16z"/>
    </svg>
  )
}

/** MingCute `star` (filled, shapes). */
export function IconStarFilled(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="currentColor" d="M10.92 2.37a1.25 1.25 0 0 1 2.16 0l2.795 4.8 5.428 1.175a1.25 1.25 0 0 1 .667 2.054l-3.7 4.142.56 5.525a1.25 1.25 0 0 1-1.748 1.27L12 19.096l-5.082 2.24a1.25 1.25 0 0 1-1.747-1.27l.559-5.525-3.7-4.142a1.25 1.25 0 0 1 .667-2.054L8.125 7.17z"/>
    </svg>
  )
}

/** MingCute `user_1` (regular, users). */
export function IconUser1(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z"/>
    </svg>
  )
}

/** MingCute `user_1` (filled, users). */
export function IconUser1Filled(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="3" d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z"/>
    </svg>
  )
}

/** MingCute `web` (regular, development). */
export function IconWeb(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="M20 11H4m3-3h.01M10 8h.01M13 8h.01M5 19h14a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1Z"/>
    </svg>
  )
}

/** MingCute `youtube` (regular, brands). */
export function IconYoutube(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeWidth="2" d="M3.232 7.808a2.8 2.8 0 0 1 2.58-2.523C7.481 5.149 9.815 5 12 5s4.52.15 6.188.285a2.8 2.8 0 0 1 2.58 2.523C20.887 9.03 21 10.572 21 12s-.113 2.97-.232 4.192a2.8 2.8 0 0 1-2.58 2.523C16.519 18.851 14.185 19 12 19s-4.52-.15-6.188-.285a2.8 2.8 0 0 1-2.58-2.523C3.113 14.97 3 13.428 3 12s.113-2.97.232-4.192Z"/><path fill="currentColor" d="M15.1 11.48a.6.6 0 0 1 0 1.04l-4.2 2.425a.6.6 0 0 1-.9-.52v-4.85a.6.6 0 0 1 .9-.52z"/>
    </svg>
  )
}
