/**
 * AUTO-GENERATED by scripts/build-icons.mjs from @mingcute/svg@3.0.2.
 * Do not edit by hand — add the icon's MingCute name to src/icons/manifest.json and run `pnpm icons`.
 *
 * Icons are sized with `width`/`height` of `1em` so they scale with the surrounding text by default;
 * a component that fixes an icon box (Button, Link) overrides that in CSS. Colour comes from
 * `currentColor`, so an icon inherits whatever it sits in. `aria-hidden` is set because these are
 * decorative next to a label — give the icon a label at the call site if it is ever used alone.
 *
 * MingCute is Apache-2.0. See node_modules/@mingcute/svg/LICENSE.
 */
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

/** MingCute `alert` (regular, system). */
export function IconAlert(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v4m0 3h.002m-8.636 3.353h17.268a.5.5 0 0 0 .433-.75L12.433 3.648a.5.5 0 0 0-.866 0L2.933 18.603a.5.5 0 0 0 .433.75"/>
    </svg>
  )
}

/** MingCute `arrow_down` (regular, arrow). */
export function IconArrowDown(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 19V4M6.343 14 12 19.657 17.657 14"/>
    </svg>
  )
}

/** MingCute `arrow_left` (regular, arrow). */
export function IconArrowLeft(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 12h15m-10 5.657L4.343 12 10 6.343"/>
    </svg>
  )
}

/** MingCute `arrow_right` (regular, arrow). */
export function IconArrowRight(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 12h15m-5 5.657L19.657 12 14 6.343"/>
    </svg>
  )
}

/** MingCute `arrow_up` (regular, arrow). */
export function IconArrowUp(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 20V5m-5.657 5L12 4.343 17.657 10"/>
    </svg>
  )
}

/** MingCute `check` (regular, system). */
export function IconCheck(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m3.514 11.83 5.657 5.656L20.485 6.172"/>
    </svg>
  )
}

/** MingCute `close` (regular, system). */
export function IconClose(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="m5.636 5.637 12.728 12.728m-12.728 0L18.364 5.637"/>
    </svg>
  )
}

/** MingCute `down` (regular, arrow). */
export function IconDown(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17.657 9.343 12 15 6.343 9.343"/>
    </svg>
  )
}

/** MingCute `external_link` (regular, files). */
export function IconExternalLink(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V8a1 1 0 0 1 1-1h6m9 2V4h-5m-5 10 9.5-9.5"/>
    </svg>
  )
}

/** MingCute `information` (regular, system). */
export function IconInformation(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8h.002M11 11h1v6h.5m8.5-5a9 9 0 1 1-18 0 9 9 0 0 1 18 0"/>
    </svg>
  )
}

/** MingCute `refresh_2` (regular, system). */
export function IconRefresh2(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M3.811 8.264A9 9 0 0 1 14.33 3.307a9 9 0 0 1 6.672 8.622c0 .08-.088.126-.154.082l-2.678-1.804c-.091-.062-.03-.205.078-.181L20 10.41m.189 5.327c-1.789 3.932-6.208 6.112-10.519 4.956a9 9 0 0 1-6.672-8.622c0-.08.088-.126.154-.082l2.678 1.805c.091.061.03.204-.078.18L4 13.59"/>
    </svg>
  )
}

/** MingCute `right` (regular, arrow). */
export function IconRight(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9.343 6.343 15 12l-5.657 5.657"/>
    </svg>
  )
}

/** MingCute `search` (regular, files). */
export function IconSearch(props: IconProps) {
  return (
    <svg
      viewBox="0 0 24 24"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="2" d="m15.879 15.879 4.242 4.242M18 10.5a7.5 7.5 0 1 1-15 0 7.5 7.5 0 0 1 15 0Z"/>
    </svg>
  )
}
