import type { ReactNode } from 'react'
import {
  IconBank,
  IconBook2,
  IconBracketsAngle,
  IconBriefcase,
  IconBuilding1,
  IconBulb,
  IconChartLine,
  IconChat1,
  IconClipboard,
  IconContacts2,
  IconContacts3,
  IconCube,
  IconDocument2,
  IconFactory,
  IconFileSearch,
  IconFolder2,
  IconGovernment,
  IconGroup3,
  IconHighVoltagePower,
  IconLayoutGrid,
  IconListSearch,
  IconLock,
  IconMortarboard,
  IconPlugin2,
  IconPresentation1,
  IconQuestion,
  IconRocket,
  IconSearch,
  IconSearchAi,
  IconSend,
  IconSettings2,
  IconSettings5,
  IconShop,
  IconShoppingBag1,
  IconShoppingCart1,
  IconTerminalBox,
  IconTool,
  IconTranslate2Ai,
  IconTruck,
  IconUser1,
  IconUser4,
  IconUserFollow2,
  IconWeb,
  IconWorld2,
} from '../icons'

/**
 * The nav's icons, by the name `site-nav.ts` records.
 *
 * A lookup rather than components in the data, for the same reason `page-schema.ts` names its icons:
 * the data stays plain serialisable values, so it can round-trip through a builder or a file.
 */
const NAV_ICONS: Record<string, ReactNode> = {
  IconBank: <IconBank />,
  IconBook2: <IconBook2 />,
  IconBracketsAngle: <IconBracketsAngle />,
  IconBriefcase: <IconBriefcase />,
  IconBuilding1: <IconBuilding1 />,
  IconBulb: <IconBulb />,
  IconChartLine: <IconChartLine />,
  IconChat1: <IconChat1 />,
  IconClipboard: <IconClipboard />,
  IconContacts2: <IconContacts2 />,
  IconContacts3: <IconContacts3 />,
  IconCube: <IconCube />,
  IconDocument2: <IconDocument2 />,
  IconFactory: <IconFactory />,
  IconFileSearch: <IconFileSearch />,
  IconFolder2: <IconFolder2 />,
  IconGovernment: <IconGovernment />,
  IconGroup3: <IconGroup3 />,
  IconHighVoltagePower: <IconHighVoltagePower />,
  IconLayoutGrid: <IconLayoutGrid />,
  IconListSearch: <IconListSearch />,
  IconLock: <IconLock />,
  IconMortarboard: <IconMortarboard />,
  IconPlugin2: <IconPlugin2 />,
  IconPresentation1: <IconPresentation1 />,
  IconQuestion: <IconQuestion />,
  IconRocket: <IconRocket />,
  IconSearch: <IconSearch />,
  IconSearchAi: <IconSearchAi />,
  IconSend: <IconSend />,
  IconSettings2: <IconSettings2 />,
  IconSettings5: <IconSettings5 />,
  IconShop: <IconShop />,
  IconShoppingBag1: <IconShoppingBag1 />,
  IconShoppingCart1: <IconShoppingCart1 />,
  IconTerminalBox: <IconTerminalBox />,
  IconTool: <IconTool />,
  IconTranslate2Ai: <IconTranslate2Ai />,
  IconTruck: <IconTruck />,
  IconUser1: <IconUser1 />,
  IconUser4: <IconUser4 />,
  IconUserFollow2: <IconUserFollow2 />,
  IconWeb: <IconWeb />,
  IconWorld2: <IconWorld2 />,
}

export function navIcon(name?: string): ReactNode {
  return name ? NAV_ICONS[name] : undefined
}
