/**
 * Generates `src/icons/generated.tsx` from the icons declared in `src/icons/manifest.json`.
 *
 * The icons come from `@mingcute/svg`, a devDependency, so the build is reproducible and offline:
 * the version is pinned by the lockfile and gated by the release-age policy in pnpm-workspace.yaml.
 * The MingCute MCP server is for *finding* an icon name interactively; it is deliberately not part of
 * this script, which must be able to run in CI.
 *
 * MingCute's `core-regular` style is a 2px stroked outline on a 24x24 grid, already authored with
 * `stroke="currentColor"` — the same construction as the icons exported from the Figma library, whose
 * names (`system/refresh_2`, `arrow/arrow_right`) are MingCute's names.
 *
 * Usage: node scripts/build-icons.mjs [--check]
 *   --check  exits non-zero if the generated file is out of date, without writing it (for CI)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = join(root, 'node_modules', '@mingcute', 'svg')
const outFile = join(root, 'src', 'icons', 'generated.tsx')
const checkOnly = process.argv.includes('--check')

const STYLES = { regular: 'core-regular', filled: 'core-filled' }

const manifest = JSON.parse(readFileSync(join(root, 'src', 'icons', 'manifest.json'), 'utf8'))

/** `arrow_right` -> `ArrowRight`. */
const pascal = (name) =>
  name
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')

/** `stroke-linecap` -> `strokeLinecap`; leaves already-camel or single-word attributes alone. */
const camel = (attr) => attr.replace(/-([a-z])/g, (_, c) => c.toUpperCase())

/** Rewrites SVG markup into JSX: hyphenated attribute names become camelCase. */
const toJsx = (markup) =>
  markup.replace(/(\s)([a-z]+(?:-[a-z]+)+)=/g, (_, space, attr) => `${space}${camel(attr)}=`)

/** Suggests close matches so a typo in the manifest is easy to fix. */
function nearest(name, all) {
  const needle = name.replace(/[_-]/g, '')
  return all
    .filter((n) => n.replace(/[_-]/g, '').includes(needle) || needle.includes(n.replace(/[_-]/g, '')))
    .slice(0, 6)
}

const components = []
const errors = []

for (const [style, dir] of Object.entries(STYLES)) {
  const names = manifest[style] ?? []
  if (!names.length) continue

  const metaPath = join(pkg, dir, 'metadata.json')
  if (!existsSync(metaPath)) {
    throw new Error(`@mingcute/svg is not installed (missing ${metaPath}). Run \`pnpm install\`.`)
  }
  const meta = JSON.parse(readFileSync(metaPath, 'utf8'))
  const byName = new Map(meta.map((m) => [m.name, m]))

  for (const name of names) {
    const entry = byName.get(name)
    if (!entry) {
      const hints = nearest(name, [...byName.keys()])
      errors.push(`  "${name}" is not a MingCute ${style} icon` + (hints.length ? ` — did you mean ${hints.join(', ')}?` : ''))
      continue
    }

    const svg = readFileSync(join(pkg, dir, entry.file), 'utf8')
    const inner = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim()
    const viewBox = (svg.match(/viewBox="([^"]+)"/) ?? [, '0 0 24 24'])[1]

    components.push({
      export: `Icon${pascal(name)}${style === 'filled' ? 'Filled' : ''}`,
      mingcute: name,
      category: entry.category,
      style,
      viewBox,
      inner: toJsx(inner),
    })
  }
}

if (errors.length) {
  console.error(`Unknown icons in src/icons/manifest.json:\n${errors.join('\n')}`)
  process.exit(1)
}

components.sort((a, b) => a.export.localeCompare(b.export))

const version = JSON.parse(readFileSync(join(pkg, 'package.json'), 'utf8')).version

const body = components
  .map(
    (c) => `/** MingCute \`${c.mingcute}\` (${c.style}, ${c.category}). */
export function ${c.export}(props: IconProps) {
  return (
    <svg
      viewBox="${c.viewBox}"
      width="1em"
      height="1em"
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden
      focusable="false"
      {...props}
    >
      ${c.inner}
    </svg>
  )
}`,
  )
  .join('\n\n')

const contents = `/**
 * AUTO-GENERATED by scripts/build-icons.mjs from @mingcute/svg@${version}.
 * Do not edit by hand — add the icon's MingCute name to src/icons/manifest.json and run \`pnpm icons\`.
 *
 * Icons are sized with \`width\`/\`height\` of \`1em\` so they scale with the surrounding text by default;
 * a component that fixes an icon box (Button, Link) overrides that in CSS. Colour comes from
 * \`currentColor\`, so an icon inherits whatever it sits in. \`aria-hidden\` is set because these are
 * decorative next to a label — give the icon a label at the call site if it is ever used alone.
 *
 * MingCute is Apache-2.0. See node_modules/@mingcute/svg/LICENSE.
 */
import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement>

${body}
`

const current = existsSync(outFile) ? readFileSync(outFile, 'utf8') : null
if (current === contents) {
  console.log(`Icon file already up to date (${components.length} icons).`)
} else if (checkOnly) {
  console.error(`stale src/icons/generated.tsx\n\nGenerated icons are out of date. Run \`pnpm icons\`.`)
  process.exit(1)
} else {
  writeFileSync(outFile, contents)
  console.log(`wrote src/icons/generated.tsx — ${components.length} icons from @mingcute/svg@${version}`)
}
